# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubekumber < Formula
  desc ""
  homepage "https://github.com/kubekumber/homebrew-tools"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kubekumber/kubekumber/releases/download/v0.0.9/kubekumber_0.0.9_Darwin_arm64.tar.gz"
      sha256 "ccafc1ecfb4101f2308112d3d6ee25357cf96738460694e918d9bad276fda2bd"

      def install
        bin.install "kubekumber"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubekumber/kubekumber/releases/download/v0.0.9/kubekumber_0.0.9_Darwin_x86_64.tar.gz"
      sha256 "9e56b621c9a93238ede097e27abaaddb617032e77e3566f59e2034bcafbfa43c"

      def install
        bin.install "kubekumber"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubekumber/kubekumber/releases/download/v0.0.9/kubekumber_0.0.9_Linux_arm64.tar.gz"
      sha256 "00ec4917903907e550e9020c4b4a5e3a02c990e9755a27a64cb149d5942e917b"

      def install
        bin.install "kubekumber"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubekumber/kubekumber/releases/download/v0.0.9/kubekumber_0.0.9_Linux_x86_64.tar.gz"
      sha256 "d87dccce75872192655ed110bcb735b08247269d451521bc40a961d8acae5fee"

      def install
        bin.install "kubekumber"
      end
    end
  end
end
